### ISSUE TITLE
Animation needs optimizing to work in Firefox

### ISSUE THREAD

**Issue by valacar** [vaalkor/DivWalker#1]
Hello. I saw your comment on [Hacker News](https://news.ycombinator.com/item?id=38014069) mentioning your DivWalker script, and when I tried it out, I noticed that in Firefox it wouldn't let me bookmark it. After some investigating I found out that Firefox limits URL length to 65536 characters and your script is around 107k, so I decided to see if I could optimize the size.

I extracted the base64 encoded images, output them to PNG files, and took them into Krita. I ran them through the Threshold filter to remove some noise (for better compression), adjusted the animation a bit (the last frame was duplicated and one or two was shifted a pixel horizontally), and then optimized the PNG file sizes with [pngquant](https://pngquant.org/) + [optipng](https://github.com/shssoichiro/oxipng) + [zopflipng](https://github.com/google/zopfli). The end result was just 7.9k for the PNG image sequence, compared to 78k previously.

After the images were optimized I re-encoded everything and put it back into the script, but personally I decided to use APNG format instead, which resulted in a script file size of 18.4k. Finally I used a web site called [Bookmarkleter](https://chriszarate.github.io/bookmarkleter/) to turn it into a bookmarklet and now I'm able to use it in Firefox :)

Anyway, I would do a pull request, but it looks like I would have to delete some files and modify your powershell script, which I don't really want to do, so I will just offer the optimized PNG files (and APNG file if you want to use that) as an [attachment zip file](https://github.com/vaalkor/DivWalker/files/13171504/divwalker-optimized.zip) for you to use if you like.

Thanks for sharing your bookmarklet :)

**Comment by vaalkor** [comment]
Awesome! I've just added the pngs in a new folder and updated the script: https://github.com/vaalkor/DivWalker/commit/7b1f58a0472274cfd012b18599a3494adfaf7375 

Glad you enjoyed my little amusement. At some point I'd like to make one that walks along the top of an element, climbs down the side, monkey bars across the bottom, then climbs the other side :)
